### ISSUE TITLE
Crash and cant download ruby on LG G4

### ISSUE THREAD

**Issue by Phurkus** [cSploit/android#254]
Just downloaded csploit earlier today. Tried latest version, second,latest version and nightly. 
Nightly wouldnt even start. The other 2 versions it kept saying ruby failed to download. If i press not to download and try any of the options from mitm it just crashes and resets my phone. 

I have a theory that its my phone, because ive been trying to get Zanti to work with my phone and zanti also acts weird with my phone. 
Any fix? 
I would like to upload a log so you can figure it out better, but not sure how to do that. 

Thanks for your time

**Comment by Tajnymag** [comment]
Could you try the 1.5.4 version? Also read all the issues before posting stuff here ;-)

**Comment by Phurkus** [comment]
@Tajnymag im actually reading through them right now. 
First day commenting, still learning the flow. And i currelty have 1.5.4 version , but still same problem

**Comment by gainan** [comment]
@Phurkus , try to get logs when you launch the app, and paste the output to pastebin.com (or if you know the exact exception/error paste it here):
https://developer.android.com/tools/debugging/debugging-log.html

I think we should write a howto about how to report bugs...

**Comment by tux-mind** [comment]
@gainan the following is the message we used to respond to users when an incomplete issue were posted.
probably I have to put this into the official website.

How to Open an Issue
---

If you find a bug, weird behaviour, missing translation, a feature not working or anything strange in the application you are encouraged to open an issue on the appropriate github page.
For your issue to be considered and solved ASAP please provide the following informations while opening it:

* Your Device model.
* Your ROM name and version.
* The version of dSploit your are running.
* As many details as possible on the network you are running dSploit on.
* A description of the issue you have, if it is a MITM feature not working, please specify if the other MITM features are working on your network.
* **[A logcat](http://forum.xda-developers.com/showthread.php?t=1726238)** taken while the application was running and the issue happened.

**Any issue which will not contain those details, will be signaled with a link to this page and closed from 24h to 48h later.**

**Comment by Phurkus** [comment]
I just uploaded what i believe is the log cat you guys mentioned. 
wasent 100% if its what your talking about, i found a page on XDA talking about how to post it.
heres the catlog link on pastebin  http://pastebin.com/SPXKkmi1

Device model is Verizon LG G4 VS986
ROM   is 5.1 lollipop
dsploit version 1.5.4

issue: i try downloading ruby and it does download, but they after the download finishes, i get a popup saying something when wrong the the download. 
File is downloaded to my internal card.

**Comment by sorano** [comment]
@Phurkus do you have supersu installed and granting csploit su rights?

Which path is your busybox installed under?

**Comment by tux-mind** [comment]
@Phurkus  it looks like the `which` utility is not installed, try to update/install busysbox please.

**Comment by sorano** [comment]
Most likely error at the user side.
Closing.

**Comment by xaitax** [comment]
@sorano You don't need to close any single issue just because you think it's right. It's not solved hence no need to close - like with several other issues.

**Comment by sorano** [comment]
Well, considering there has been lots of development over the last few days and this user hasn't returned for 5 days and his device does not contain the which utlilty I would most likely say its an end-user issue and not cSploit issue.
Do you disagree?

Of course the user is free to re-open the issue once he has tried out the latest version and has verified his busybox installation.

**Comment by Phurkus** [comment]
Hello, sorry for delay, ive been busy with some essays and havent had some time to get back on here.

I did NOT have busybox installed, so I downloaded and installed afew minutes ago. After that i went to download csploit 1.6 RC i believe it was called. (latest verison)

On first startup it said a core could not be found for my device. App closed itself. 

On second relaunch it continues where it left of and begins updating itself, it now has problem on the msf download. It downloads, extracts gems, and says an error occurred during download.

With busybox i let it update and i clicked install. Is there extra steps i should take with busybox? 

Im gonna try to play with older versions of csploit and see what happens.

**Comment by sorano** [comment]
Some users have had success with installing busybox under /system/xbin/ instead of the default path.

Once you have finished testing read this on how to file an issue that the developers can actually use to solve the problem:
https://github.com/cSploit/android/wiki/How-to-open-an-issue

**Comment by tux-mind** [comment]
Hii @Phurkus , don't blame yourself about the delay, every one here has a real life, after all :grin: 

it would be great if you can share a logcat taken after the problem occurs. try out the [catlog](https://play.google.com/store/apps/details?id=com.nolanlawson.logcat) app! it can be used to record the logcat to a file on your sdcard, simple to share :wink: 

thanks for your patience and time :blush:

**Comment by Phurkus** [comment]
@sorano busybox is installed under /system/xbin/ 

@tux-mind thanks for positive reply, i know it can be annoying teaching someone that doesnt really understand so im trying my best here to do my part 😃
 i have the catlog app, its how i got the log cat from the first one. I opened log cat and quickly opened csploit after to avoid clicking other stuff cuz more code would write out, lol. 
Is there a way to specify logcat of csploit only? 
Il post another logcat in afew minutes 😊😊😊

**Comment by tux-mind** [comment]
@Phurkus in past someone else had to teach me those stuff, we are happy to teach to those pupils eager to learn :wink:

I don't think that you can filter the logcat from the catlog app. also in case of some native crash the logcat will not include some important info.

looking forward for your logcat :blush:

**Comment by Phurkus** [comment]
@tux-mind very true, and computers have always been a fasination for me 😀😀 

Heres the link to the logcat, im gonna sleep its 3:50 am and im prolly gonna be tired in the morning. Il get back on here in the morning. Hope it helps 😊☺
http://pastebin.com/NRgVGt3T

**Comment by tux-mind** [comment]
hi @Phurkus , I have some bad news for your :disappointed: 

your logcat shows a native crash int the ruby executable and your android system cannot attach to the process to dump an useful stacktrace for debugging the issue.

but I have an idea that might solve the problem.
download [this gem](https://rubygems.org/downloads/bundler-1.10.6.gem) and put it on your sdcard.

connect your phone to the pc and open an adb shell.

run those commands:

```sh
su
mkdir -p /data/data/org.csploit.android/files/ruby/lib/ruby/gems/1.9.1/cache/
cp /sdcard/bundler-1.10.6.gem /data/data/org.csploit.android/files/ruby/lib/ruby/gems/1.9.1/cache/
```

and restart the msf update.
feel free to ask any help about the process and thanks for your time :blush:

**Comment by Phurkus** [comment]
@tux-mind hii, i wasnet home most of the day. And i have i linux laptop so i was googling how to adb from linux. I will install the sdk tomorrow. 😃😃😃
I tried to put the code from a terminal emulator on my phone by giving it root permission. 
But i ran into abit of trouble with the last code,saying its just a directory? Maybe i misunderstood something. 

If im correct all the code is doing is moving,the downloaded gem into a cache folder right? Could i just manually move it there with a file explorer? Or is the code nessicary?

**Comment by Phurkus** [comment]
@tux-mind **update

I got the terminal code working. I had to replace
cp /sdcard/bundler-1.10.6.gem

With 

cp /storage/external_SD/bundler-1.10.6.gem

After that a tried to start csploit but there was only a blank screen. So i reinstalled csploit, and before opening it i re-entered the terminal code. 
Now when it runs and checks to update, its falling on the core? 😓😓 
I feel like im making progression tho. Can you share a link to the core that i could manually put? Or where should we go from this direction?

**Comment by tux-mind** [comment]
try installing the [nightly build](http://rootbitch.cc/csploit/cSploit-nightly.apk), we fixed the first boot core issue there.

thanks for all your efforts @Phurkus , really appreciated :blush:

**Comment by Phurkus** [comment]
@tux-mind no problem, 😊😊😊 thanks for giving me your time to help me out. I really appriciate that.

So i tried to the nightly and the core updated successfully ((: 

Now the problem is with updating msf. It downloads successfully, then when installing is where it fails. 

I still put the ruby gems in the cache folder like earlier

**Comment by tux-mind** [comment]
oh oh oh.
I just achieved that you have the XPosed framework installed on your device.

please try to uninstall it and let me know.
it try to block/control any root process on your device, including cSploit ones.

thanks for your time :blush:

**Comment by Phurkus** [comment]
You mean uninstall xposed framework?
I have an app from xposed called xprivacy, but i allow all control for csploit.

**Comment by tux-mind** [comment]
yeah, I mean that app.
you allow full control to cSploit, but processes spawned by cSploit doesn't belong to an app.

let me known :blush:

**Comment by Phurkus** [comment]
I just deleted xprivacy, but still same issue. il try deleting xposed right now

**Comment by Phurkus** [comment]
heres a logcat of the info.
http://pastebin.com/iJQgu1SP
problem is still the same.

have the nightlies been updated ? il try on those agian. how often do the nightlies get updated?

**Comment by xaitax** [comment]
Usually every 5 hours. But in the past few days I pushed updates more regularly. Might change it to hourly since @tux-mind reduced the build-time tremendously. :+1:

**Comment by Phurkus** [comment]
@xaitax wow that is some serious work you guys putting in 😀😀😀😀 much appriciated 👏👏 and thabks for the info, il try nightly in a bit

**Comment by Phurkus** [comment]
@tux-mind so nightlies dont work, the newest update still doesnt work. im just gonna wait it out and maybe some day in the future an update will work (: thanks for all the time and effort guys

**Comment by tux-mind** [comment]
@sorano this issue isn't resolved yet :wink:

@Phurkus thanks for the logcat, it looks like you didn't totally removed the Xposed framework, I can see it's stuff in the logcat.

how ever I will release an apk for you to debug this issue.
I'll keep you posted.

thanks for your great collaboration :wink:

**Comment by Phurkus** [comment]
@tux-mind yeah i didnt want to completly remove xposed 😏☺ and thank you, greatly appriciate your work 👏😀

**Comment by Phurkus** [comment]
@tux-mind just checking in to say the latest version of csploit has downloaded and updaded ruby, msf, and core with no probs. Il test it out later on, and il report if working.
Thanks agian mate for all your efforts 😄😄
Excited to try out

**Comment by tux-mind** [comment]
gald to hear that @Phurkus 

feel free to reopen the issue if the problem still present.
