### ISSUE TITLE
Cannot update core, nor ruby and msf.

### ISSUE THREAD

**Issue by PoToNN** [cSploit/android#269]
Version 1.5.4
Samsung galaxy s3
Stock rom 4.3 rooted.
Have Busybox pro and SuperSu. Both up to date.
Here is the logcat:
http://pastebin.com/cUcqxTF4
Ps:This logcat has only the core install error. Not the ruby and msf.

After installation csploit downloades core 1.0.5 but can not be installed after extraction. It says cannot find a core for this device and cannot start process. I see a notification about SuperSu granting root permission to csploit but when I open SuperSu csploit is not on the list of applications.Anyways csploit repeats same error when I try to open until I reboot. After reboot it opens without error but it gives errors for ruby and msf installation.

**Comment by Rubenoo** [comment]
Tip: try gist.github.com

**Comment by tux-mind** [comment]
@PoToNN looks like a daemon error.

can you please share `/data/data/org.csploit.android/files/cSploitd.log` ?
thanks for the report :blush:

**Comment by tux-mind** [comment]
it looks like it's a #1 related issue.
please share `/data/data/org.csploit.android/files/start_daemon.log`

**Comment by mcilya** [comment]
Have ruby and msf part of this problem.
start_daemon.log & csploitd.log: http://pastebin.com/u1Xci2n7

**Comment by tux-mind** [comment]
Hi @mcilya , I think that your issue differs from @PoToNN one.

your core starts successfully, the @PoToNN one does not.

however to debug your problem post a logcat also :heart:

**Comment by mcilya** [comment]
A catlog with attempt to install core, but failed: http://pastebin.com/5bLyVfkz

**Comment by tux-mind** [comment]
You're right, same stuff.
Will fix it ASAP.

**Comment by PoToNN** [comment]
Sorry, it was a really busy day :/ I guess you don't need the log anymore :D Thanks mcilya

**Comment by tux-mind** [comment]
hey guys, can you share `/data/data/org.csploit.android/files/cSploitd.log` ?
thanks in advance.

**Comment by PoToNN** [comment]
https://www.dropbox.com/s/6ry85pqgf207070/cSploitd?dl=0

**Comment by tux-mind** [comment]
@PoToNN the log, not the daemon ( `cSploitd.log` )

don't worry, everyone make mistakes ( except chuck norris :laughing: )

**Comment by mcilya** [comment]
csploitd.log: http://pastebin.com/AtUm1Ls3

**Comment by PoToNN** [comment]
That was the only file named csploitd in that folder. I am a true noobie man :D

**Comment by mcilya** [comment]
@PoToNN Don't worry sometimes file can be not created. Try start/stop app till it create :smiley:

**Comment by PoToNN** [comment]
Oh I see now it is created. Thanks :) By the way, core 1.0.6 also gives the same error.

**Comment by mcilya** [comment]
csploid.log & start_daemon.log + catlog:   http://pastebin.com/YVPpMLNi
P.S. Sorry if spam :blush:

**Comment by Rubenoo** [comment]
cSploit is crashing on lastest branch,while trying to install core
samsung galaxy s5, android 5 
logcat : https://gist.github.com/Rubenoo/c0bc3fd857d00790cd5c

**Comment by sorano** [comment]
I think this was solved in version 1.6.0 RC2.

**Comment by tux-mind** [comment]
no @sorano this wasn't solved yet, thanks anyway for maintaining the issues :wink:
